#this playbook uses cisco.ios.ios_config module located at:
#https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_config_module.html#cisco-ios-ios-config-manage-cisco-ios-configuration-sections

#start Ansible Playbook with 3 dashes. Make sure indentation throughout the Playbook is correct.
---

#we name our first Play and let Ansible know which host(s) to target for this play
- name: Play 1 - Work on Cisco devices                  
  hosts: cisco                                          
   #we don't Ansible to gather facts from our network hosts
  gather_facts: no                                     

  tasks:
    #we name our task 
    - name: Task 1 - Take backup                        
      #we'll use 'cisco.ios.ios_config' module to perform backup
      cisco.ios.ios_config:                            
            #parameters for the module
            backup: yes                                 
            #specify options e.g. filename and location, 
            #otheriwse will be saved in /backup folder with default name
            backup_options:                            
              filename: r119944.cfg
              dir_path: ./config_backups
              
      